name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - jwoo92
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: affected-webpage
    attributes:
      label: What is the affected webpage?
      placeholder: ex. database-answers.com/path/to/webpage
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Brave
        - Chrome
        - Firefox
        - Microsoft Edge
        - Opera
        - Safari
  - type: dropdown
    id: environments
    attributes:
      label: What environments are you seeing the problem on?
      multiple: true
      options:
        - Android
        - iOS
        - Linux
        - Mac
        - Windows
